development:
  graph_root: /api/graph/
  auth_root: /api/auth/
test:
  graph_root: http://localhost:4000/api/graph/
  auth_root: http://localhost:4000/api/auth/
service_development:  
  graph_root: http://localhost:3332/
  auth_root: http://localhost:3333/
service_test:  
  graph_root: http://localhost:3336/
  auth_root: http://localhost:3335/
staging:
  graph_root: https://graph.core.gmah.net/
  auth_root: https://auth.core.gmah.net/
acceptance:
  graph_root: /api/graph/
  auth_root: /api/auth/
