development:
  auth_root: http://localhost:3333/
styling:
  auth_root: http://styling.local:3333/
test:
  auth_root: http://localhost:3335/
staging:
  auth_root: https://auth-staging.coreon.com/
production:
  auth_root: https://auth.coreon.com/
